// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockResearchPlatform.Data;

#nullable disable

namespace StockResearchPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230221212459_Add-Migration mutualfund")]
    partial class AddMigrationmutualfund
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StockResearchPlatform.Models.Stock", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("CIK")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Ticker");

                    b.ToTable("Stocks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Stock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StockResearchPlatform.Models.MutualFundClass", b =>
                {
                    b.HasBaseType("StockResearchPlatform.Models.Stock");

                    b.Property<string>("classID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("seriesID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("MutualFundClass");
                });
#pragma warning restore 612, 618
        }
    }
}
