// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockResearchPlatform.Data;

#nullable disable

namespace StockResearchPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230220025917_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StockResearchPlatform.Models.Stock", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("CIK")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Ticker");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
